AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_crud_op

  Sample SAM Template for sam_crud_op

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        USER_TABLE: UserTable
        END_POINT: https://8000-amitaegisconvena-awssam-my7f6ah6pdo.ws-us105.gitpod.io


Parameters:
  Table:
    Type: String
    Default: User

Resources:
  handlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: handler.handler
      Policies: 
        - DynamoDBCrudPolicy:
            TableName : UserTable
      Events:
        creatUser:
          Type: Api 
          Properties:
            Path: /user
            Method: post
        getUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: get
        listUsers:
          Type: Api 
          Properties:
            Path: /users
            Method: get
        updateUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: put
        deleteUser:
          Type: Api 
          Properties:
            Path: /user/{id}
            Method: delete

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  CreateUserLocalEndpoint:
    Description: "Local endpoint URL for createUser function"
    Value: "http://localhost:3000/user"

  DeleteUserLocalEndpoint:
    Description: "Local endpoint URL for deleteUser function"
    Value: "http://localhost:3000/user/{id}"

  GetUserLocalEndpoint:
    Description: "Local endpoint URL for getUser function"
    Value: "http://localhost:3000/user/{id}"

  ListUserLocalEndpoint:
    Description: "Local endpoint URL for listUser function"
    Value: "http://localhost:3000/users"

  UpdateUserLocalEndpoint:
    Description: "Local endpoint URL for updateUser function"
    Value: "http://localhost:3000/user/{id}"

