AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_crud_op

  Sample SAM Template for sam_crud_op

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        USER_TABLE: !Ref Table
        REGION_NAME: !Ref Region

Parameters:
  Table:
    Type: String
    Default: User
  Region:
    Type: String
    Default: in-north-1

Resources:
  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: createUser.createUser
      Policies: 
        - DynamoDBCrudPolicy:
            TableName : !Ref UserTable
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: post
  listUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: listUsers.listUsers
      Policies: 
        - DynamoDBCrudPolicy:
            TableName : !Ref UserTable
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: get
  
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    # Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    # Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    # Value: !GetAtt HelloWorldFunctionRole.Arn
